/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPoliceRouteImport } from './routes/_authenticated/police'
import { Route as AuthenticatedCitizenRouteImport } from './routes/_authenticated/citizen'
import { Route as AuthenticatedPoliceIndexRouteImport } from './routes/_authenticated/police.index'
import { Route as AuthenticatedCitizenIndexRouteImport } from './routes/_authenticated/citizen.index'
import { Route as ApiPublicPredictRouteImport } from './routes/api/public/predict'
import { Route as AuthenticatedPoliceLogRouteImport } from './routes/_authenticated/police.log'
import { Route as AuthenticatedPoliceHeatmapRouteImport } from './routes/_authenticated/police.heatmap'
import { Route as AuthenticatedPoliceChalansRouteImport } from './routes/_authenticated/police.chalans'
import { Route as AuthenticatedPoliceAnalyticsRouteImport } from './routes/_authenticated/police.analytics'
import { Route as AuthenticatedCitizenChalansRouteImport } from './routes/_authenticated/citizen.chalans'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPoliceRoute = AuthenticatedPoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitizenRoute = AuthenticatedCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliceIndexRoute =
  AuthenticatedPoliceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedCitizenIndexRoute =
  AuthenticatedCitizenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCitizenRoute,
  } as any)
const ApiPublicPredictRoute = ApiPublicPredictRouteImport.update({
  id: '/api/public/predict',
  path: '/api/public/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPoliceLogRoute = AuthenticatedPoliceLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedPoliceRoute,
} as any)
const AuthenticatedPoliceHeatmapRoute =
  AuthenticatedPoliceHeatmapRouteImport.update({
    id: '/heatmap',
    path: '/heatmap',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceChalansRoute =
  AuthenticatedPoliceChalansRouteImport.update({
    id: '/chalans',
    path: '/chalans',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceAnalyticsRoute =
  AuthenticatedPoliceAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedCitizenChalansRoute =
  AuthenticatedCitizenChalansRouteImport.update({
    id: '/chalans',
    path: '/chalans',
    getParentRoute: () => AuthenticatedCitizenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/citizen': typeof AuthenticatedCitizenRouteWithChildren
  '/police': typeof AuthenticatedPoliceRouteWithChildren
  '/citizen/chalans': typeof AuthenticatedCitizenChalansRoute
  '/police/analytics': typeof AuthenticatedPoliceAnalyticsRoute
  '/police/chalans': typeof AuthenticatedPoliceChalansRoute
  '/police/heatmap': typeof AuthenticatedPoliceHeatmapRoute
  '/police/log': typeof AuthenticatedPoliceLogRoute
  '/api/public/predict': typeof ApiPublicPredictRoute
  '/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/police/': typeof AuthenticatedPoliceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/citizen/chalans': typeof AuthenticatedCitizenChalansRoute
  '/police/analytics': typeof AuthenticatedPoliceAnalyticsRoute
  '/police/chalans': typeof AuthenticatedPoliceChalansRoute
  '/police/heatmap': typeof AuthenticatedPoliceHeatmapRoute
  '/police/log': typeof AuthenticatedPoliceLogRoute
  '/api/public/predict': typeof ApiPublicPredictRoute
  '/citizen': typeof AuthenticatedCitizenIndexRoute
  '/police': typeof AuthenticatedPoliceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/citizen': typeof AuthenticatedCitizenRouteWithChildren
  '/_authenticated/police': typeof AuthenticatedPoliceRouteWithChildren
  '/_authenticated/citizen/chalans': typeof AuthenticatedCitizenChalansRoute
  '/_authenticated/police/analytics': typeof AuthenticatedPoliceAnalyticsRoute
  '/_authenticated/police/chalans': typeof AuthenticatedPoliceChalansRoute
  '/_authenticated/police/heatmap': typeof AuthenticatedPoliceHeatmapRoute
  '/_authenticated/police/log': typeof AuthenticatedPoliceLogRoute
  '/api/public/predict': typeof ApiPublicPredictRoute
  '/_authenticated/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/_authenticated/police/': typeof AuthenticatedPoliceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/citizen'
    | '/police'
    | '/citizen/chalans'
    | '/police/analytics'
    | '/police/chalans'
    | '/police/heatmap'
    | '/police/log'
    | '/api/public/predict'
    | '/citizen/'
    | '/police/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/citizen/chalans'
    | '/police/analytics'
    | '/police/chalans'
    | '/police/heatmap'
    | '/police/log'
    | '/api/public/predict'
    | '/citizen'
    | '/police'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/citizen'
    | '/_authenticated/police'
    | '/_authenticated/citizen/chalans'
    | '/_authenticated/police/analytics'
    | '/_authenticated/police/chalans'
    | '/_authenticated/police/heatmap'
    | '/_authenticated/police/log'
    | '/api/public/predict'
    | '/_authenticated/citizen/'
    | '/_authenticated/police/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicPredictRoute: typeof ApiPublicPredictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/police': {
      id: '/_authenticated/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof AuthenticatedPoliceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen': {
      id: '/_authenticated/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof AuthenticatedCitizenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police/': {
      id: '/_authenticated/police/'
      path: '/'
      fullPath: '/police/'
      preLoaderRoute: typeof AuthenticatedPoliceIndexRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/citizen/': {
      id: '/_authenticated/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof AuthenticatedCitizenIndexRouteImport
      parentRoute: typeof AuthenticatedCitizenRoute
    }
    '/api/public/predict': {
      id: '/api/public/predict'
      path: '/api/public/predict'
      fullPath: '/api/public/predict'
      preLoaderRoute: typeof ApiPublicPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/police/log': {
      id: '/_authenticated/police/log'
      path: '/log'
      fullPath: '/police/log'
      preLoaderRoute: typeof AuthenticatedPoliceLogRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/heatmap': {
      id: '/_authenticated/police/heatmap'
      path: '/heatmap'
      fullPath: '/police/heatmap'
      preLoaderRoute: typeof AuthenticatedPoliceHeatmapRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/chalans': {
      id: '/_authenticated/police/chalans'
      path: '/chalans'
      fullPath: '/police/chalans'
      preLoaderRoute: typeof AuthenticatedPoliceChalansRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/analytics': {
      id: '/_authenticated/police/analytics'
      path: '/analytics'
      fullPath: '/police/analytics'
      preLoaderRoute: typeof AuthenticatedPoliceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/citizen/chalans': {
      id: '/_authenticated/citizen/chalans'
      path: '/chalans'
      fullPath: '/citizen/chalans'
      preLoaderRoute: typeof AuthenticatedCitizenChalansRouteImport
      parentRoute: typeof AuthenticatedCitizenRoute
    }
  }
}

interface AuthenticatedCitizenRouteChildren {
  AuthenticatedCitizenChalansRoute: typeof AuthenticatedCitizenChalansRoute
  AuthenticatedCitizenIndexRoute: typeof AuthenticatedCitizenIndexRoute
}

const AuthenticatedCitizenRouteChildren: AuthenticatedCitizenRouteChildren = {
  AuthenticatedCitizenChalansRoute: AuthenticatedCitizenChalansRoute,
  AuthenticatedCitizenIndexRoute: AuthenticatedCitizenIndexRoute,
}

const AuthenticatedCitizenRouteWithChildren =
  AuthenticatedCitizenRoute._addFileChildren(AuthenticatedCitizenRouteChildren)

interface AuthenticatedPoliceRouteChildren {
  AuthenticatedPoliceAnalyticsRoute: typeof AuthenticatedPoliceAnalyticsRoute
  AuthenticatedPoliceChalansRoute: typeof AuthenticatedPoliceChalansRoute
  AuthenticatedPoliceHeatmapRoute: typeof AuthenticatedPoliceHeatmapRoute
  AuthenticatedPoliceLogRoute: typeof AuthenticatedPoliceLogRoute
  AuthenticatedPoliceIndexRoute: typeof AuthenticatedPoliceIndexRoute
}

const AuthenticatedPoliceRouteChildren: AuthenticatedPoliceRouteChildren = {
  AuthenticatedPoliceAnalyticsRoute: AuthenticatedPoliceAnalyticsRoute,
  AuthenticatedPoliceChalansRoute: AuthenticatedPoliceChalansRoute,
  AuthenticatedPoliceHeatmapRoute: AuthenticatedPoliceHeatmapRoute,
  AuthenticatedPoliceLogRoute: AuthenticatedPoliceLogRoute,
  AuthenticatedPoliceIndexRoute: AuthenticatedPoliceIndexRoute,
}

const AuthenticatedPoliceRouteWithChildren =
  AuthenticatedPoliceRoute._addFileChildren(AuthenticatedPoliceRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCitizenRoute: typeof AuthenticatedCitizenRouteWithChildren
  AuthenticatedPoliceRoute: typeof AuthenticatedPoliceRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCitizenRoute: AuthenticatedCitizenRouteWithChildren,
  AuthenticatedPoliceRoute: AuthenticatedPoliceRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicPredictRoute: ApiPublicPredictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
